name: Formatting and lint checks

on:
  push:
  pull_request:

jobs:
  formatting_and_lint_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18" # ensure that we are tracking the current LTS

      - name: Install dependencies
        run: npm ci

      - name: Prettier
        run: npm run stylecheck

      - name: Lint
        run: npm run lint

      - name: Typechecks
        run: npm run typecheck
