name: Get deployment url
on:
  pull_request:
    types:
      - opened
      - synchronize # Triggered when the PR branch is updated


jobs:
  wait-for-vercel-deployment:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: wpNgD5yXygHl4aT700JKq3lX
        with:
          vercel_project_id: 'prj_dqyXyjUF6y4biivZFImL1VuDOAfX'
      - name: Get URL
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"
